### PR TITLE
fix(wakunode2): move node config inside app init branch

### LINKED ISSUE #2422: bug: RLN registration fails on exception: field 'clusterId' is not accessible
### Problem
When running interop tests with latest NWaku docker image, RLN registration fails. 

### Impact
high occurrence, medium severity

### To reproduce
1) Rerun workflow .github/workflows/nim_waku_rln.yml available at commit https://github.com/waku-org/waku-interop-tests/commit/633e774dd2b65acc60aa04aa6d7cb9d112474760

### Expected behavior
RLN registration is successful.  

### Screenshots/logs
DEBUG    src.node.waku_node:waku_node.py:164 container log: /app/apps/wakunode2/wakunode2.nim(70) wakunode2
DEBUG    src.node.waku_node:waku_node.py:164 container log: /app/vendor/nimbus-build-system/vendor/Nim/lib/system/chcks.nim(42) raiseFieldError2
DEBUG    src.node.waku_node:waku_node.py:164 container log: /app/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(54) sysFatal
DEBUG    src.node.waku_node:waku_node.py:164 container log: Error: unhandled exception: field 'clusterId' is not accessible for type 'WakuNodeConf' using 'cmd = generateRlnKeystore' [FieldDefect]

### nwaku version/commit hash
harbor.status.im/wakuorg/nwaku:latest
Docker image: 
"Created": "2024-02-12T14:36:29.571056389Z"
"Id": "sha256:68ac4eeafb068abb25be5ccc1cf88914ccd832e044abd0e5cfb1c209f987ddc9"

### PR DESCRIPTION
**Pull request by rymnc**
# Description

Moves the TWN default config into the wakunode2 default sub-command branch (i.e run the wakunode), instead of running it before the keystore generator subcommand

# Changes

- [x] reordered node init

## How to test

1. `make -j16 wakunode2`, run the keystore generator

## Issue

closes #2422

### CODE REVIEW

File: apps/wakunode2/wakunode2.nim [hunk 1]
```diff
@@ -97,15 +78,35 @@ when isMainModule:
...
+      conf.rlnRelayDynamic = twnClusterConf.rlnRelayDynamic
+      conf.rlnRelayBandwidthThreshold = twnClusterConf.rlnRelayBandwidthThreshold
+      conf.discv5Discovery = twnClusterConf.discv5Discovery
+      conf.discv5BootstrapNodes =
+        conf.discv5BootstrapNodes & twnClusterConf.discv5BootstrapNodes
+
     var wakunode2 = App.init(rng, conf)
 
+    info "Running nwaku node", version = app.git_version
+    logConfig(conf)
```
Comment (Ivansete-status) [inline apps/wakunode2/wakunode2.nim:107]: In general, it looks great to me this PR but does it do any harm having the version shown above?

Comment (rymnc) [reply apps/wakunode2/wakunode2.nim:107]: it doesn't but i don't think there is any merit in printing that log while running the keystore generator

**Review by romanzac — APPROVED** [review]
LGTM!
