### PR TITLE
fix: updates regex pattern to support username:password authentication in http/https URLs

### LINKED ISSUE #3512: feat: support basic auth for rln-relay-eth-client-address
### Problem

Having `https://login:pass@example.com/some/path` is not supported:

```
Failed to load secondary sources: 'Serialisation error while processing /conf/config.toml:Invalid HTTP RPC URL'
```

### Suggested solution

Probably it's not difficult to support basic auth using the underlying library.

### Alternatives considered

Alternatively I will need to run a local proxy.

### PR DESCRIPTION
**Pull request by ashiskumarnaik**
fixes #3512

### CODE REVIEW

File: waku/factory/external_config.nim [hunk 1]
```diff
@@ -749,10 +749,12 @@ proc parseCmdArg*(T: type EthRpcUrl, s: string): T =
   ## http://url/with/path
   ## http://url:port/path?query
   ## https://url:port/path?query
+  ## https://user:pass@url:port/path
+  ## http://username:password@url:port/path
   ## disallowed patterns:
   ## any valid/invalid ws or wss url
   var httpPattern =
-    re2"^(https?):\/\/([\w-]+(\.[\w-]+)*)(:[0-9]{1,5})?(\/[\w.,@?^=%&:\/~+#-]*)?$"
```
Comment (fryorcraken) [inline waku/factory/external_config.nim:755]: I would recommended extracting that and adding some unit tests to get high confidence on correctness.

Comment (vpavlin) [reply waku/factory/external_config.nim:755]: Curious if the usage of `\w` limits what the password can contain - some unit tests would definitely help uncover the limitations:)

File: tests/factory/test_external_config.nim [hunk 2]
```diff
@@ -259,3 +259,87 @@ suite "Waku external config - Shards":
 
     ## Then
     assert res.isErr(), "Invalid shard was accepted"
+
+suite "Waku external config - EthRpcUrl parsing":
```
Comment (Ivansete-status) [inline tests/factory/test_external_config.nim]:
```suggestion
suite "Waku external config - http url parsing":
```

**Review by darshankabariya — COMMENTED** [review]
Thanks for taking care ! 
LGTM

**Comment by Ivansete-status** [comment]
Thanks @ashiskumarnaik !
We need though the commits to have a verified signature:
Kindly follow the next steps and re-commit again: https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

Your commits should have the "Verified" label. See for example:

image

Thanks!

**Comment by fryorcraken** [comment]
> We need though the commits to have a verified signature:

I would recommend the maintainers of the repo (you), to rebase and resign commits for signatures.

Signatures of external contributors do not matter as much as signatures of core contributors.
