### PR TITLE
fix(waku_keystore): sigsegv on different appInfo

### LINKED ISSUE #1934: bug: SIGSEGV with RLN
Using `c369b3294e48c947a624b09b38be7c3666e2d9e6`

When running
```
./build/wakunode2 \
--rln-relay=true \
--rln-relay-dynamic=true \
--rln-relay-cred-password=password \
--rln-relay-cred-path=rlnKeystore.json \
--rln-relay-eth-contract-address=0x2992c7bFD42729991b614e95F4C2C78619f49c50  \
--rln-relay-tree-path=rln_tree.db \
--rln-relay-eth-client-address=YOUR_INFURA_SEPOLIA_ENDPOINT \
--log-level=debug
```

I get:

```
DBG 2023-08-23 16:02:24.981+02:00 1/7 Setting up storage                     topics="wakunode main" tid=7172450 file=wakunode2.nim:59
DBG 2023-08-23 16:02:24.981+02:00 2/7 Retrieve dynamic bootstrap nodes       topics="wakunode main" tid=7172450 file=wakunode2.nim:67
DBG 2023-08-23 16:02:24.981+02:00 No method for retrieving dynamic bootstrap nodes specified. topics="wakunode app" tid=7172450 file=app.nim:224
DBG 2023-08-23 16:02:24.981+02:00 3/7 Initializing node                      topics="wakunode main" tid=7172450 file=wakunode2.nim:74
DBG 2023-08-23 16:02:24.981+02:00 no peer storage found                      tid=7172450 file=peer_manager.nim:425
INF 2023-08-23 16:02:24.981+02:00 Initializing networking                    tid=7172450 file=waku_node.nim:143 addrs=@[/ip4/89.130.215.58/tcp/60000]
DBG 2023-08-23 16:02:24.981+02:00 4/7 Mounting protocols                     topics="wakunode main" tid=7172450 file=wakunode2.nim:81
INF 2023-08-23 16:02:24.982+02:00 mounting relay protocol                    topics="waku node" tid=7172450 file=waku_node.nim:316
INF 2023-08-23 16:02:24.982+02:00 relay mounted successfully                 topics="waku node" tid=7172450 file=waku_node.nim:335
DBG 2023-08-23 16:02:24.982+02:00 subscribe                                  topics="waku node" tid=7172450 file=waku_node.nim:234 pubsubTopic=/waku/2/default-waku/proto
DBG 2023-08-23 16:02:24.982+02:00 subscribe                                  topics="waku relay" tid=7172450 file=protocol.nim:199 pubsubTopic=/waku/2/default-waku/proto
INF 2023-08-23 16:02:24.982+02:00 mounting rendezvous discovery protocol     topics="waku node" tid=7172450 file=waku_node.nim:848
INF 2023-08-23 16:02:24.982+02:00 mounting libp2p ping protocol              topics="waku node" tid=7172450 file=waku_node.nim:806
INF 2023-08-23 16:02:24.982+02:00 mounting rln relay                         topics="waku node" tid=7172450 file=waku_node.nim:737
DBG 2023-08-23 16:02:24.982+02:00 rln-relay input validation passed          topics="waku node" tid=7172450 file=rln_relay.nim:400
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
zsh: segmentation fault  ./build/wakunode2 --rln-relay=true --rln-relay-dynamic=true
```

My keystore is:
```
{"application": "nwaku-rln-relay", "appIdentifier": "01234567890abcdef", "credentials": [{"crypto": {"cipher": "aes-128-ctr", "ciphertext":
"ca2fa895eb16ba355f3b44be89eb1e9500b1f64627881f57d7f3b3e0a653040e4224cc8e261833ae56573309b58d9300850eef8d7dd31497f908978d861110b24bae3a273ebc4fe09502f840e1c141860f8d3d847c1ce0c52b1c874493ebdc52315e54a70329e06ab80bf95e1fa06f94f80db2e91a85460afebee9d8030f0a18b62723af9e5125f32ac03c9999abbd9d505a70a22620bde58d40fb0513b21f993a1f9ade796a44f5bafba2e1aa539b9f2731018f61700cb28e2e1eb5121e8653d7fb9f80d2323931730adcc44d1a01bb2d27bb8e3d044517e1b16ec77a70a21e93ee62a6c34081329dae6bd18c4cdca92fdca389e70bc63c71445ed0ff8eef3bae68c9db46984a051d14ddc01009ba4cc9fb22c09b5fe06912c55a28ea48ec7a739fcad9aaa77a4938ff3f32af385417ec8944b7ed2291febd1cfa58b589eadb785c3a8911a8bca28e06fec5a8023f4add99624fd79601b195daec08bb215fc9432776fd71d90845dfb10689d1e3182dc6a40f18626587c77a62e248e7a70b5283a86ad24b3ca42e8b7825a5b3af7e9706f6d1fa86e8bb6a3f14cc1ce5eaafe4d708a4469e2b2f36cdcd47ed0cb98db4514fcc11a28124103c1d106e7958e30b5395da342bce329d935dab6b2d187980fbaa71f97a124847867cb5953c6e81f040703f1fb3177e11813340124e053539cf8c6f5421d63d8d1de9f7c58423f7efa74d36b5e8002648de7e50e67f4e0523f2cdd54349cfc630d6d51660d1fde0b0944a3926f678bae65863bd90d220d96356c4d5f3b80c7c15cf9ff4715659766e1e451080952f8929ef0eef30c387ade66f6cd0cace742b304326cac62e7a5d833b391a10f9c67a886e87add5e10a0828ae4f1b73f83137e7eb8729e13e4d93e3534cf29fd7ac3b8194db4204b01b74b4f6c814dd78d20db62fbdeb5d6fd5604c665856b266f24250ea99c5",
"cipherparams": {"iv": "46d8d4507d204503d8b13862960adfb9"}, "kdf": "scrypt", "kdfparams": {"dklen": 32, "n": 262144, "p": 1, "r": 8, "salt":
"d385ce4e09edef856b1eeb68e76a971d41d9ad8b3d66b16177ea05936883365f"}, "mac": "7eb437a193ac9ac55d408830841fa4b82253d4b2f8b87c024ab0a24dd56c870c"}}], "version": "0.1"}
```

Running only the following (same without `rln-relay-eth-contract-address` it works)
```
./build/wakunode2 \
--rln-relay=true \
--rln-relay-dynamic=true \
--rln-relay-cred-password=password \
--rln-relay-eth-contract-address=0x2992c7bFD42729991b614e95F4C2C78619f49c50  \
--rln-relay-tree-path=rln_tree.db \
--rln-relay-eth-client-address=wss://sepolia.infura.io/ws/v3/4576482c0f474483ac709755f2663b20 \
--log-level=debug
```

Any idea?

### PR DESCRIPTION
**Pull request by rymnc**
- **fix(waku_keystore): sigsegv on different appInfo**

# Description

The `matchingAppKeystore` is set only when a match is found, else it is returned as void. This PR converts it to an option and adds a check before returning it so that we dont segfault :)

# Changes

- [x] converted `matchingAppKeystore` to an Option
- [x] added test for this vector

## Issue

closes #1934

### CODE REVIEW

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks! :100:

File: waku/waku_keystore/keystore.nim [hunk 1]
```diff
@@ -101,7 +101,15 @@ proc loadAppKeystore*(
   except IOError:
     return err(AppKeystoreError(kind: KeystoreIoError, msg: getCurrentExceptionMsg()))
 
-  return ok(matchingAppKeystore)
+  if matchingAppKeystore.isNone():
```
Comment (alrevuelta) [inline waku/waku_keystore/keystore.nim:104]: Perhaps this is too generic? Will make it difficult to debug. I would suggest handling each mismatch and being more verbose with the errors:

```
  if data["application"].getStr() != appInfo.application:
    error1
  if data["appIdentifier"].getStr() != appInfo.appIdentifier:
    error2
  if data["version"].getStr() != appInfo.version:
    error3
...
```

**Review by alrevuelta — APPROVED** [review]
lgtm with a minor comment.

File: waku/waku_keystore/keystore.nim (hunk 1 above)
Comment (rymnc) [reply waku/waku_keystore/keystore.nim]: this is the error log now, thanks:
```
ERR 2024-05-01 18:19:03.684+05:30 App initialization failed                  topics="wakunode main" tid=102289 file=wakunode2.nim:139 error="Failed setting up node: Mounting protocols failed: failed to mount waku RLN relay protocol: failed to mount WakuRlnRelay: could not initialize the group manager: failed to get the keystore credentials: keystore error: JSON value mismatch: Application does not match. Expected 'waku-rln-relay' but got 'nwaku-rln-relay'"
```
