### PR TITLE
fix(rln-relay): handle empty metadata returned by getMetadata proc

### LINKED ISSUE #2471: chore: avoid execution error: metadata does not exist from ./register_rln.sh
### Background
nwaku-compose starting a node always shows a confusing error.

### Details
Every time the `./regiser_rln.sh` script is executed, the following error appears and we should avoid that because it causes confusion:
`execution error: metadata does not exist`

This can be tested from: https://github.com/waku-org/nwaku-compose

### PR DESCRIPTION
**Pull request by rymnc**
- **fix(rln-relay): silence error on startup when metadata is not found**
- **chore: fix fetching value from option**

# Description

This PR silences the execution error that is received when trying to fetch the rln metadata from the db.
Zerokit's PR: https://github.com/vacp2p/zerokit/pull/231
If it returns a buf of len 0, then we assume the metadata is not found, and proceed execution as usual.

# Changes

- [x] updated rln static lib version to v0.3.6
- [x] updated zerokit submodule
- [x] added test for empty metadata returned

## How to test

1. `make -j16 test`

## Issue

closes #2471

### CODE REVIEW

File: waku/waku_rln_relay/group_manager/on_chain/group_manager.nim [hunk 1]
```diff
@@ -669,8 +669,8 @@ method init*(g: OnchainGroupManager): Future[void] {.async.} =
   let metadataGetRes = g.rlnInstance.getMetadata()
   if metadataGetRes.isErr():
     warn "could not initialize with persisted rln metadata"
-  else:
-    let metadata = metadataGetRes.get()
+  elif metadataGetRes.get().isSome():
+    let metadata = metadataGetRes.get().get()
```
Comment (rymnc) [inline waku/waku_rln_relay/group_manager/on_chain/group_manager.nim:673]: not the cleanest, but oh well

**Review by gabrielmer — APPROVED** [review]
LGTM, thanks so much! 🤩

**Review by Ivansete-status — APPROVED** [review]
LGTM! Thanks! :100:
