### PR TITLE
fix(rln-relay): bump zerokit to v0.3.2

### LINKED ISSUE #1944: bug: rln db disappears
### Problem

There are two different issues that might be related. I must admit that a bit hard to reproduce:
* nwaku's rln database seems to disappear after stopping the node and starting it again.
  * -1 start nwaku
  * -2 db is created
  * -3 stop waku
  * -4 start waku (db disappears and is never created. waku runs without an rln database)
  * -5 stop waku
  * -6 start
  * -and then we jump to 1 again in a loop
* valid messages are rejected with "provided root does not belong to acceptable window of roots". Perhaps expected since the tree is incorrect.

### How to reproduce

4539dfc76109382f321080fdfbf92e44531c6de8
Almost to copy paste, but replace your `rln-relay-eth-client-address`

Run node 1 and wait until its in sync.

```
./build/wakunode2 \
--rln-relay=true \
--rpc-address=0.0.0.0 \
--rpc-admin=true \
--rln-relay-dynamic=true \
--rln-relay-cred-password=password \
--rln-relay-cred-path=rlnKeystore_1.json \
--rln-relay-tree-path=rln_tree_1.db \
--rln-relay-eth-contract-address=0x2992c7bFD42729991b614e95F4C2C78619f49c50  \
--rln-relay-eth-client-address=XXX \
--nodekey=161c2836197e8918d7eb1039758423795f0dc697a018ed55d5931aa9b0e5efb3 \
--log-level=debug
```

Run node 2 (connecting to node 1) and wait until its in sync

```
./build/wakunode2 \
--rln-relay=true \
--rln-relay-dynamic=true \
--rln-relay-cred-password=password \
--rln-relay-cred-path=rlnKeystore_2.json \
--rln-relay-tree-path=rln_tree_2.db \
--rln-relay-eth-contract-address=0x2992c7bFD42729991b614e95F4C2C78619f49c50  \
--rln-relay-eth-client-address=XXX \
--staticnode=/ip4/127.0.0.1/tcp/60000/p2p/16Uiu2HAm2ZuRHGZUzG6JGJeY1nGKHXLGrQYnZ7mZToymHtFfYFFf \
--ports-shift=1 \
--log-level=debug
```

Publish a message via node 1 rpc

```
curl http://localhost:8545 -d '{"jsonrpc":"2.0","method":"post_waku_v2_relay_v1_message","params":["/waku/2/default-waku/proto", {"payload": "SGkgdGhlcmUgZXRoY2M=", "timestamp": 1, "contentTopic": "some-topic", "ephemeral": false}],"id":1}' -H 'Content-Type: application/json'
```

At this point this messages may arrive ok.

But, if you stop both nodes, and start them again, after being in sync, messages will be rejected with the following. Perhaps its expected because in this second run, nwaku removes the rln db and never creates it again. Very weird.

```
invalid message: provided root does not belong to acceptable window of roots topics="waku rln_relay" tid=8135039 file=rln_relay.nim:213 provided=1c6434f20ce741009c72d8d6aae37183d50bf093349b0bd82fc3906859612077 validRoots=@[]
```

cat rlnKeystore_1.json

```
{"application":"waku-rln-relay","appIdentifier":"01234567890abcdef","credentials":[{"crypto":{"cipher":"aes-128-ctr","ciphertext":"2d6ccc6cfe7580d6b6fa8effb308b0481ea1f2a8bf3f00f4ca9918007d3ad52b55be71889b4b789d67222189b8ddde5e3f700b35f5ff75e6b4df50e40020a2028748dc19376d7748512aacbb7c134f16df2e27be0978bd5708bbabf71f4b9be3cd95b7f90cab66becb942c1a9e2e03b3309b224bdbc5ea223921922f39742c3d455b9022cbde10df376085bcb2fb63989de32350b018e4ffd1b5e706e269f3160f8d44c1416725652781c8f58ea937d02fcf5f9d4bd8888ff2bba54d9cf7bcd43f4e0466d12f35d78e9517c16bd9e9d3755a276e9e29ef91bbda5d8d2ea5c9e25fccc24a94ae0a4ca477daf2bc9169b34ef080a18c140c364bbb7a47799a32eeaa2cd7b42a60dd83f1e4c3c67d0b12316211acf69d83b542ac346840085e855118573fc626ee0c450a841cc232e8b525c5263a601889accd3996fa65e5a6a0b7f9be948020399dfdd2bb9d715c55253819151cd1523d54ba6be0e6141c0aadc0fa3124376908711c3f19e3dbc13367db5d240c1da230bdf02fbc475533d3f78bc45ddb98259edfc5e6f18767c100d2c50b641baf8d38180fe684a9ed97a868a38500daedaed248cc9a835a11d3b87e7ef3fae5220bfd541a5c46ddae6413289cedfb67faa9a2a276dd14cb0d41ec367ab52eb4b5886a316dc9597e9c7541587e7e5de10b17c31e28f46965d39a0160e189625f44308323e330a62f9da5de6f70b42ebf02fba637220431da25cb002427a6487b572586d8bdb5368242ac0822dc4ede3baa65bfa812b3fcb1f46c6a75879ddc2becddab681b26960f6785ac326996d30bce035c266120cd898ea1c31af61267103d55046d897c1b019a9334e8677cad31bfd06b70652f5606565ae56b38dddece09c30c2192630b45b3665a7af009c075dd772c139648ae8bd6a1b2bf5bdb723746582fdedac1e5971b44c580027457711b4b1bb8f92119294d66a0e2916d","cipherparams":{"iv":"e673f2715981a20152bfcba937088c84"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"8705afec2d76c26fcf29ed7799fd223c0de06bc0b48114d819e716099899a195"},"mac":"bb09d98bac48ba887c9265f2c0d7933043c6e3804eef201e1c63640f60a17a02"}}],"version":"0.1"}
```

cat rlnKeystore_2.json
```
{"application":"waku-rln-relay","appIdentifier":"01234567890abcdef","credentials":[{"crypto":{"cipher":"aes-128-ctr","ciphertext":"1a299e6d29ede153c6f848570c89c3fb76cec70ae31fb609eb89ba3a8b7bb6bfeed5c7dd5f9b40798bc3d81afb50aa0493e7ba254e0a2b3fa55ef0d4f8f8bb8277c1cd0d8a6d3aac9b1650a1af1d25d3bbcee18a06294835e686d929a432fdc7a7f669608779eb2de10a690ada470efbb1e266d2558dcd49e364da64ecbb77daeca753e44a8229acfef56416798f45d08bb24ad16b243659264b38d8507e186828a72e907da7709570f32a418629734051fe31a7e0a1439406039aa500798915e04c9c7e94ed7ac1c0d10e5e8f5f0363d4bc9a89e8b5165fda1074e049d5b1a1fbd35c8b3fa937e228c636fc3184ea2730496d4a7cb21c13462c6ffdfbb5c6783e71db7a5b576b1133540a6d6300c342d5d364a58a85874ae7005f7c9071518f61ca46443367f138bc31af8edecfdf219cde178713bfa66ec5dd050488c0b2e199bbef85707bfd1231cf26acf6ab4f7a9bf79d197632ee0039e646c521ea12f77c959e58cf076c129d86e05cb05b8a45fe5c787ed57665b8767c9f6bf054062bf2607054054a9c87d9d378d2bfe4f6eee47c63349bec7daa2268c3e0c9305396ca865b6a9105c8a2af70494d2e5c00b8f0feb0ea76863ea8851d288a7f613a2f1da2c229b91153af8867350b092a2102d91c0ed4ae85aeacd7b2fb47a1c1ab7dfc23f92c7ac079cd3c017dfb80df8495d27ec9982e20b18468cce8c60ef1db9b10705f80f8fc93aeb990b1fbfc8ef6b7133ef84a392974beaae4328ccbeecadb9d898cea37fe6e598ae91229bb369b4318e948bb5a4d99b62135f2145be459c80dabde4de9e3b4d46569696422b04ab212a9efa79cd5f59db5ab9928db54c31ec01f2b4b2fabc7e7eac7bcd15f212f25c1f9ad26c709c12c95d5f9d729088e9290ee488c8587f2328f48a44c7539f7eaf0828a8c0fcdf2e99b817f8b6236","cipherparams":{"iv":"975168c825dbba8d655b03ef6a27acbb"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"741d639c1526900e32e9cc9d387b3e5f405700051eda280fdf26f37b3cb8e248"},"mac":"ff7815401e851ddea93c4610d3ba908c14ae031f804cc2de9944aeb3c7cdc4cc"}}],"version":"0.1"}
```

### PR DESCRIPTION
**Pull request by rymnc**
# Description

Bumps zerokit to v0.3.2, which includes a fix for tree persistence

# Changes

- [x] Updated .gitmodules zerokit branch
- [x] Updated zerokit submodule
- [x] Updated `build_rln.sh`

## Issue

closes #1944

### CODE REVIEW

**Comment by rymnc** [comment]
@alrevuelta can you confirm that this branch does not produce the bug you mentioned?

File: scripts/build_rln.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@ fi
 host_triplet=$(rustup show | grep "Default host: " | cut -d' ' -f3)
 
 # Download the prebuilt rln library if it is available
-if curl --silent --fail-with-body -L "https://github.com/vacp2p/zerokit/releases/download/v0.3.1/$host_triplet-rln.tar.gz" >> "$host_triplet-rln.tar.gz"
+if curl --silent --fail-with-body -L "https://github.com/vacp2p/zerokit/releases/download/v0.3.2/$host_triplet-rln.tar.gz" >> "$host_triplet-rln.tar.gz"
```
Comment (vpavlin) [inline scripts/build_rln.sh:20]: Maybe an unnecessary overkill, but what about getting the version from the submodule?

Something like 

```
$ git submodule status vendor/zerokit | awk '{print $3}' | sed 's/[()]//g'
v0.3.1
``` 

So that there is only one source of truth for the version?

**Review by vpavlin — APPROVED** [review]
blocked on @alrevuelta's review, but otherwise ok:)

**Review by alrevuelta — APPROVED** [review]
lgtm! indeed it fixes the issue of the db disappearing every second run. Thanks for such a quick fix. I must admit it was very very tricky to reproduce 😢

File: scripts/build_rln.sh (hunk 1 above)
Comment (rymnc) [reply scripts/build_rln.sh:20]: will address in a follow up pr, thanks!
