### PR TITLE
fix: duplicate message forwarding in filter service

### LINKED ISSUE #2320: bug: Filter relay/v1/messages GET returns duplicate messages
### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Have a relay node (node1)
2. Connect a filter node (node2) to the relay node
3. Subscribe to some topics and verify that messages published via Relay reach the Filter nodes
4. Publish a message via Relay and verify that the filter node get's that message
5. Publish again the same message via Relay and verify if the filter node get's that message

### Actual behavior
Filter message receives again the message

### Expected behavior
I think this is a bug because:
- if the node2 is relay instead of filter, and we use `relay/v1/messages` instead the duplicate message will not be retrieved.
- if instead of nwaku I use gowaku for the exact scenario,  the duplicate message will not be retrieved.

### Screenshots/logs
If applicable, add screenshots or logs to help explain your problem.

### nwaku version/commit hash
harbor.status.im/wakuorg/nwaku:latest

### Docker logs

[node2_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwakulatest.log](https://github.com/waku-org/nwaku/files/13779745/node2_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwaku.latest.log)
[node1_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwakulatest.log](https://github.com/waku-org/nwaku/files/13779747/node1_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwaku.latest.log)

### Test logs
```
17:59:51 src.node.docker_mananger DEBUG Starting container with image harbor.status.im/wakuorg/nwaku:latest
17:59:51 src.node.docker_mananger DEBUG Using args ['--listen-address=0.0.0.0', '--rpc=true', '--rpc-admin=true', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=44660', '--rpc-port=44658', '--rest-port=44657', '--tcp-port=44659', '--discv5-udp-port=44661', '--rpc-address=0.0.0.0', '--rest-address=0.0.0.0', '--nat=extip:172.18.94.194', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=44662', '--metrics-logging=true', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']
17:59:52 src.node.docker_mananger DEBUG Container started with ID c1fe65c40472. Setting up logs at ./log/docker/node1_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwaku:latest.log
17:59:52 src.node.waku_node DEBUG Started container from image harbor.status.im/wakuorg/nwaku:latest. RPC: 44658 REST: 44657 WebSocket: 44660 TCP: 44659
17:59:52 src.libs.common DEBUG Sleeping for 1 seconds
17:59:53 src.node.api_clients.base_client INFO GET call: http://127.0.0.1:44657/debug/v1/info with payload: None
17:59:53 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.94.194/tcp/44659/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.94.194/tcp/44660/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-Kq4QGOifM6PYEcE460guogZZmU02OuKKPY26vXpn7h1rNUjYQpIcxUkUQNqKj2canKOCuBf_R2ax1TQfkt_ClNwIxYBgmlkgnY0gmlwhKwSXsKKbXVsdGlhZGRyc4wACgSsEl7CBq503QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCrnODdWRwgq51hXdha3UyBQ"}'
17:59:53 src.node.waku_node INFO REST service is ready !!
17:59:53 src.steps.filter DEBUG Running fixture setup: setup_main_filter_node
17:59:53 src.node.docker_mananger DEBUG Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
17:59:53 src.node.waku_node DEBUG WakuNode instance initialized with log path ./log/docker/node2_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwaku:latest.log
17:59:53 src.node.waku_node DEBUG Starting Node...
17:59:53 src.node.docker_mananger DEBUG Attempting to create or retrieve network waku
17:59:53 src.node.docker_mananger DEBUG Network waku already exists
17:59:53 src.node.docker_mananger DEBUG Generated random external IP 172.18.225.164
17:59:53 src.node.docker_mananger DEBUG Generated ports [17456, 17457, 17458, 17459, 17460, 17461]
17:59:53 src.node.docker_mananger DEBUG Starting container with image harbor.status.im/wakuorg/nwaku:latest
17:59:53 src.node.docker_mananger DEBUG Using args ['--listen-address=0.0.0.0', '--rpc=true', '--rpc-admin=true', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=17459', '--rpc-port=17457', '--rest-port=17456', '--tcp-port=17458', '--discv5-udp-port=17460', '--rpc-address=0.0.0.0', '--rest-address=0.0.0.0', '--nat=extip:172.18.225.164', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=17461', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QGOifM6PYEcE460guogZZmU02OuKKPY26vXpn7h1rNUjYQpIcxUkUQNqKj2canKOCuBf_R2ax1TQfkt_ClNwIxYBgmlkgnY0gmlwhKwSXsKKbXVsdGlhZGRyc4wACgSsEl7CBq503QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCrnODdWRwgq51hXdha3UyBQ', '--filternode=/ip4/172.18.94.194/tcp/44659/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
17:59:53 src.node.docker_mananger DEBUG Container started with ID 0050531e2af7. Setting up logs at ./log/docker/node2_2023-12-27_17-59-51__a326b384-8ecf-45e5-a65a-081f58c49657__harbor.status.im_wakuorg_nwaku:latest.log
17:59:53 src.node.waku_node DEBUG Started container from image harbor.status.im/wakuorg/nwaku:latest. RPC: 17457 REST: 17456 WebSocket: 17459 TCP: 17458
17:59:53 src.libs.common DEBUG Sleeping for 1 seconds
17:59:54 src.node.api_clients.base_client INFO GET call: http://127.0.0.1:17456/debug/v1/info with payload: None
17:59:54 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.225.164/tcp/17458/p2p/16Uiu2HAmH3yEtwB7D9gb8fBU6N7734FopFLxFHae3zkYRcDWhetS","/ip4/172.18.225.164/tcp/17459/ws/p2p/16Uiu2HAmH3yEtwB7D9gb8fBU6N7734FopFLxFHae3zkYRcDWhetS"],"enrUri":"enr:-Kq4QKoEkDYoDZlsW16QPFj5SjmnI7KDDvgxC2ti4MuCOTYbJH8TYZqTzAt_fwMT4PNbmItPKa1Ux7Fle_0nv4IHtD8BgmlkgnY0gmlwhKwS4aSKbXVsdGlhZGRyc4wACgSsEuGkBkQz3QOJc2VjcDI1NmsxoQNBUdnY-zsexRNeE7UR8bTGw9EtMkpBM0ZlFJwCBGEeK4N0Y3CCRDKDdWRwgkQ0hXdha3UyBA"}'
17:59:54 src.node.waku_node INFO REST service is ready !!
17:59:54 src.steps.filter DEBUG Running fixture setup: subscribe_main_nodes
17:59:54 src.node.api_clients.base_client INFO POST call: http://127.0.0.1:44657/relay/v1/subscriptions with payload: ["/waku/2/rs/0/0"]
17:59:54 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'OK'
17:59:54 src.node.api_clients.base_client INFO POST call: http://127.0.0.1:17456/filter/v2/subscriptions with payload: {"requestId": "4a1437f6-03e6-4122-99d9-ed5e30c969c6", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/0"}
17:59:54 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'{"requestId":"4a1437f6-03e6-4122-99d9-ed5e30c969c6","statusCode":0,"statusDesc":""}'
------------------------------------------------------------------------------------------------ live log call ------------------------------------------------------------------------------------------------
17:59:55 src.node.api_clients.base_client INFO POST call: http://127.0.0.1:44657/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0 with payload: {"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": 1703692795000859136}
17:59:55 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'OK'
17:59:55 src.libs.common DEBUG Sleeping for 0.1 seconds
17:59:55 src.steps.filter DEBUG Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the published message
17:59:55 src.node.api_clients.base_client INFO GET call: http://127.0.0.1:17456/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto with payload: None
17:59:55 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1703692795000859136}]'
17:59:55 src.node.api_clients.base_client INFO POST call: http://127.0.0.1:44657/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0 with payload: {"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": 1703692795000859136}
17:59:55 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'OK'
17:59:55 src.libs.common DEBUG Sleeping for 0.1 seconds
17:59:55 src.steps.filter DEBUG Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the published message
17:59:55 src.node.api_clients.base_client INFO GET call: http://127.0.0.1:17456/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto with payload: None
17:59:55 src.node.api_clients.base_client INFO Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1703692795000859136}]'
```

### PR DESCRIPTION
**Pull request by darshankabariya**
close #2320 

PR Description:

We identified a duplicate issue in the filter node service, which has been resolved in this fix.

### CODE REVIEW

**Review by gabrielmer — APPROVED** [review]
Looks great! Thanks so much!

**Comment by NagyZoltanPeter** [comment]
+ consideration upon re-reading the original problem:

So in Florin's test there were no relay involved. He was sending messages via REST API to relay it, but also the same node was serving filter subs. In this case filter gets the messages before relay, hence the message push.
I don't know if it's a generic case to prepare for.
All because from waku_relay there will be no such case happening as duplicates are filtered. In case of publish unfortunately filterHandler is called before any checks - due gossipsub publish calls pubsub ancestor's publish method ahead off anything - which actually calls the data handlers....

So it maybe a bit costly to maintain dup check database for this only case. 
Also the case described here is a bit strange, if there is a new message (published again) in the system why should we prevent our subscribers to get it?

**Comment by darshankabariya** [comment]
Hi @NagyZoltanPeter, I want to clarify that when I mentioned 'relay message,' I meant 'send message,' not using Waku relay. Let's set aside dynamic subscription for now and focus on the original issue. Regarding your suggestion about not needing to store messages for every peer, I'm considering using a shared hash pool. I have a question: could you please advise on how long we should cache these messages for? Currently, the default is set to just 10 milliseconds.

**Comment by NagyZoltanPeter** [comment]
> Hi @NagyZoltanPeter, I want to clarify that when I mentioned 'relay message,' I meant 'send message,' not using Waku relay. Let's set aside dynamic subscription for now and focus on the original issue. Regarding your suggestion about not needing to store messages for every peer, I'm considering using a shared hash pool. I have a question: could you please advise on how long we should cache these messages for? Currently, the default is set to just 10 milliseconds.

Ok, I see. Sorry, maybe I was not very clear.
So filter protocol will push messages to its subscribed clients (filter-client and not REST user here). It can happen from two source: relaying a message by our node or from publish (when our node introduce a message to the network).
Florin's case was the latter. 
First case filter will know messages from relay if they are valid and not duplicates. For publish case there is no such check currently because of the architecture of pubsub and gossipsub classes.

In case a message comes filter collects subscribed peers and right away sends them the message. There is no message cache involved here. 
There is a message cache but only for REST API where the REST client must poll the filtered messages. But for this case there is one message cache for the only local REST user client, there is no multi tenant query supported.

Back to your question. Gossipsub retains seen message lookup for 2 minutes. I don't think any such solution if applied should hold for more time. - but still it is a question of requirements with it what we would like to prevent with this solution? 

`Currently, the default is set to just 10 milliseconds.` What exactly is it and where?

**Comment by darshankabariya** [comment]
> > Hi @NagyZoltanPeter, I want to clarify that when I mentioned 'relay message,' I meant 'send message,' not using Waku relay. Let's set aside dynamic subscription for now and focus on the original issue. Regarding your suggestion about not needing to store messages for every peer, I'm considering using a shared hash pool. I have a question: could you please advise on how long we should cache these messages for? Currently, the default is set to just 10 milliseconds.
> 
> Ok, I see. Sorry, maybe I was not very clear. So filter protocol will push messages to its subscribed clients (filter-client and not REST user here). It can happen from two source: relaying a message by our node or from publish (when our node introduce a message to the network). Florin's case was the latter. First case filter will know messages from relay if they are valid and not duplicates. For publish case there is no such check currently because of the architecture of pubsub and gossipsub classes.
> 
> In case a message comes filter collects subscribed peers and right away sends them the message. There is no message cache involved here. There is a message cache but only for REST API where the REST client must poll the filtered messages. But for this case there is one message cache for the only local REST user client, there is no multi tenant query supported.
> 
> Back to your question. Gossipsub retains seen message lookup for 2 minutes. I don't think any such solution if applied should hold for more time. - but still it is a question of requirements with it what we would like to prevent with this solution?
> 
> `Currently, the default is set to just 10 milliseconds.` What exactly is it and where?

Thanks, @NagyZoltanPeter. now is more clear to me. If we create and publish a message, and then publish the same message again, why should we prevent our subscribers from seeing it a second time? I assume there might be scenarios where we publish the same message with the same timestamp. If the payload is the same but the timestamp is different, our fix will not stop the second message from being published. However, let's ask Florin for further clarification. 

For the sake of implementation, I will proceed with the timed cache logic to help me better understanding. If, as you mentioned, this concern is not necessary, we will not merge the PR.

Hi @fbarbu15, Could you please help us with our confusion ?

**Comment by NagyZoltanPeter** [comment]
> Thanks, @NagyZoltanPeter. now is more clear to me. If we create and publish a message, and then publish the same message again, why should we prevent our subscribers from seeing it a second time? I assume there might be scenarios where we publish the same message with the same timestamp. If the payload is the same but the timestamp is different, our fix will not stop the second message from being published. However, let's ask Florin for further clarification.
> 
> Regarding the timeout variable, it's a default variable, so we can adjust it as needed. That's why I'm asking what value we should use for our solution. [Default Timeout](https://github.com/vacp2p/nim-libp2p/blob/d0af3fbe8559f69195657a360c3dd4ac4552c811/libp2p/protocols/pubsub/timedcache.nim#L19)

I see, thank you. In this case not the default is used but [this](https://github.com/vacp2p/nim-libp2p/blob/d0af3fbe8559f69195657a360c3dd4ac4552c811/libp2p/protocols/pubsub/gossipsub.nim#L68).
 
> For the sake of implementation, I will proceed with the timed cache logic to help me better understanding. If, as you mentioned, this concern is not necessary, we will not merge the PR.
> 
> Hi @fbarbu15, Could you please help us with our confusion ?

I think this kind of duplicates is possible if:
- the filter service is on the same node as
   - used for lightpush
   - used with REST API POST relay

Other case, the more generic one is when filter service pushes messages got from relay.
It does not mean it cannot be a problem. We might consider other ways to do it.

But all in all, the message hash dup check with a timed manner is a possible good solution. Just do avoid uncontrolled message hash collection. We do expect to run pretty long and handling enormous amount of messages and this would lead to using all memory after some point.

File: waku/waku_filter_v2/protocol.nim [hunk 1]
```diff
@@ -176,20 +178,30 @@ proc pushToPeers(
   let msgHash =
     messagePush.pubsubTopic.computeMessageHash(messagePush.wakuMessage).to0xHex()
 
-  notice "pushing message to subscribed peers",
-    pubsubTopic = messagePush.pubsubTopic,
-    contentTopic = messagePush.wakuMessage.contentTopic,
-    target_peer_ids = targetPeerIds,
-    msg_hash = msgHash
+  wf.messageCache.expire(Moment.now())
+  if wf.messageCache.contains(msgHash):
```
Comment (NagyZoltanPeter) [inline waku/waku_filter_v2/protocol.nim:182]:
```suggestion
  if wf.messageCache.put(msgHash):
```

I think this is simpler and does exactly the same. It will call expire and will refresh timestamp also.

File: waku/waku_filter_v2/protocol.nim [hunk 2]
```diff
@@ -176,20 +178,30 @@ proc pushToPeers(
...
-    let pushFut = wf.pushToPeer(peerId, bufferToPublish)
-    pushFuts.add(pushFut)
+    for peerId in peers:
+      let pushFut = wf.pushToPeer(peerId, bufferToPublish)
+      pushFuts.add(pushFut)
+    await allFutures(pushFuts)
 
-  await allFutures(pushFuts)
+  ## expiration refreshed that's why update cache every time, even if it has a value.
+  discard wf.messageCache.put(msgHash, Moment.now())
```
Comment (NagyZoltanPeter) [inline waku/waku_filter_v2/protocol.nim:204]:
```suggestion
```
This is not needed in case my previous suggestion above applied.

File: waku/waku_filter_v2/protocol.nim [hunk 3]
```diff
@@ -295,6 +307,7 @@ proc new*(
       subscriptionTimeout, maxFilterPeers, maxFilterCriteriaPerPeer
     ),
     peerManager: peerManager,
+    messageCache: init(TimedCache[string], timeout = 2.minutes),
```
Comment (NagyZoltanPeter) [inline waku/waku_filter_v2/protocol.nim:310]: I would personally add the cache timeout as an input argument to the WakuFilter's new because it enables configurability even if most cases default is choosern.
Also it enables to create very easy unit tests that checks the feature correctness automatically.
So in unit test this way you can apply 1.seconds timeout which is more than enough to check such dup cases.
WDYT?

**Review by NagyZoltanPeter — APPROVED** [review]
Seems much much better! 
I added some short suggestions and if you may consider adding unit tests to check dup cases.

File: waku/waku_filter_v2/protocol.nim (hunk 3 above)
Comment (darshankabariya) [reply waku/waku_filter_v2/protocol.nim:310]: Yes, this feels like a hard-coded solution. Let's set 2 minutes as the default and allow the Waku filter to modify it as needed.
